universe = vanilla

error = $(Cluster).$(Process).mfcl.err
log = $(Cluster).$(Process).mfcl.log
output = $(Cluster).$(Process).mfcl.out

requirements = (OpSys == "LINUX")
request_cpus = 1
request_memory = 6000
request_disk = 400000

executable = condor_doitall.yft

should_transfer_files = YES
TRANSFER_INPUT_FILES = doitall-arni, mfclo64, mfcl.cfg, yft.ini, yft.frq, yft.tag, yft.age_length

when_to_transfer_output = ON_EXIT_OR_EVICT
transfer_output_files = 00.par

queue
